# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/imgInPL/imgInPL.srcs/sources_1/bd/design_wrapper/ip/design_wrapper_processing_system7_0_0/design_wrapper_processing_system7_0_0.xci
# IP: The module: 'design_wrapper_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/imgInPL/imgInPL.gen/sources_1/bd/design_wrapper/ip/design_wrapper_processing_system7_0_0/design_wrapper_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_wrapper_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/imgInPL/imgInPL.srcs/sources_1/bd/design_wrapper/ip/design_wrapper_processing_system7_0_0/design_wrapper_processing_system7_0_0.xci
# IP: The module: 'design_wrapper_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/user/imgInPL/imgInPL.gen/sources_1/bd/design_wrapper/ip/design_wrapper_processing_system7_0_0/design_wrapper_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_wrapper_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
