# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/long_wire.xdc

# Block Designs: bd/design_wrapper/design_wrapper.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_wrapper || ORIG_REF_NAME==design_wrapper} -quiet] -quiet

# IP: bd/design_wrapper/ip/design_wrapper_processing_system7_0_0/design_wrapper_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_wrapper_processing_system7_0_0 || ORIG_REF_NAME==design_wrapper_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_wrapper/ip/design_wrapper_xlconcat_0_0/design_wrapper_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_wrapper_xlconcat_0_0 || ORIG_REF_NAME==design_wrapper_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_wrapper/ip/design_wrapper_imginfile_0_0/design_wrapper_imginfile_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_wrapper_imginfile_0_0 || ORIG_REF_NAME==design_wrapper_imginfile_0_0} -quiet] -quiet
