#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Feb 28 11:50:06 CET 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim design_wrapper_wrapper_behav -key {Behavioral:sim_1:Functional:design_wrapper_wrapper} -tclbatch design_wrapper_wrapper.tcl -protoinst "protoinst_files/design_wrapper.protoinst" -log simulate.log"
xsim design_wrapper_wrapper_behav -key {Behavioral:sim_1:Functional:design_wrapper_wrapper} -tclbatch design_wrapper_wrapper.tcl -protoinst "protoinst_files/design_wrapper.protoinst" -log simulate.log

